config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  resources :bank_accounts
  resources :clients do
    resources :bank_accounts, controller: "clients/bank_accounts", except: [:index, :show, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post "bank_accounts/new_transaction", to: "bank_accounts#new_transaction"
    end
  end
end

app/views/shared/_header.html.haml
%header.main-header
  %a.logo{ href: "#" }
    %span.logo-mini
      %b
        B
      NK
    %span.logo-lg
      %b
        BETA
      Bank
  %nav.navbar.navbar-static-top
    %a.sidebar-toggle{ href: "#", data: { toggle: "push-menu" }, role: "button" }
      %span.sr-only
        Toggle Navigation
    .navbar-custom-menu
      %ul.nav.navbar-nav
        %li.dropdown.user.user-menu
          %a.dropdown-toggle{ href: "#", data: { toggle: "dropdown"}, "aria-example": true }
            = image_tag "", class: "user-image"
            %span.hidden-xs
              #{current_user.username} (#{current_user.role})
          %ul.dropdown-menu
            %li.user-header
              = image_tag "", class: "img-circle", alt: "User Image"
              %p
                #{current_user.full_name}
            %li.user-body
              #{current_user.email}
            %li.user-footer
              .pull-right
                = link_to destroy_user_session_path, class: "btn btn-danger", method: :delete do
                  .fa.fa-times
                  Sign Out

app/views/shared/_sidebar.html.haml
%aside.main-sidebar
  %section.sidebar{ style: "height: auto" }
    %ui.sidebar-menu
      %li.header
        MAIN NAVIGATION
      %li{ class: "#{params[:controller] == 'clients' ? 'active' : ''}"}
        = link_to clients_path do
          %i.fa.fa-user
          %span
            Clients
      %li{ class: "#{params[:controller] == 'bank_accounts' ? 'active' : ''}"}
        = link_to bank_accounts_path do
          %i.fa.fa-money
          %span
            Bank Accounts