config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  resources :bank_accounts
  resources :clients do
    resources :bank_accounts, controller: "clients/bank_accounts", except: [:index, :show, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post "bank_accounts/new_transaction", to: "bank_accounts#new_transaction"
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :middle_name, presence: true
  validates :client_number, presence: true, uniqueness: true

  has_many :bank_accounts

  before_save :format_name

  def format_name
    self.first_name  = self.first_name.upcase
    self.last_name   = self.last_name.upcase
    self.middle_name = self.middle_name.upcase
  end

  def num_accounts
    bank_accounts.count
  end

  def to_s
    "#{last_name}, #{first_name} #{middle_name}"
  end
end

app/controllers/clients/bank_accounts_controller.rb
module Clients
  class BankAccountsController < ApplicationController
    before_action :load_parent_object
    before_action :load_object, only: [:edit, :update]

    def new
      @bank_account = BankAccount.new
    end

    def create
      @bank_account = BankAccount.new(bank_accounts_params)
      @bank_account.client = @client

      if @bank_account.save
        redirect_to bank_account_path(@bank_account.id)
      else
        render "new"
      end
    end

    def edit
    end

    def update
      @bank_account.client = @client
      if @bank_account.update(bank_accounts_params)
        redirect_to bank_account_path(@bank_account.id)
      else
        render "edit"
      end
    end

    private

    def load_parent_object
      @client = Client.find(params[:client_id])
    end

    def load_object
      @bank_account = BankAccount.find(params[:id])
    end

    def bank_accounts_params
      params.require(:bank_account).permit(:account_number )
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to client_path(@client.id)
    else
      render "new"
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(client_params)
      redirect_to client_path(@client.id)
    else
      render "edit"
    end
  end

  def destroy
    @client = Client.find(params[:id])

    if @client.balance > 0
      redirect_to client_path(@client.id)
    else
      @client.destroy!
      redirect_to clients_path
    end
  end

  def show
    @client = Client.find(params[:id])
  end

  private
  def client_params
    params.require(:client).permit(:client_number, :first_name, :middle_name, :last_name)
  end
end

app/views/clients/_bank_accounts.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Account Number
      %th Balance
      %th Actions
  %tbody
    - bank_accounts.each do |bank_account|
      %tr
        %td #{bank_account.account_number}
        %td #{number_to_currency(bank_account.balance, unit: "P")}
        %td
          = link_to bank_account_path(bank_account.id), class: "btn btn-info" do
            Show

app/views/clients/_form.html.haml
= simple_form_for client do |f|
  .row
    .col-md-12
      = f.input :client_number,  input_html: { class: "form-control" }
  .row
    .col-md-4
      = f.input :first_name, input_html: { class: "form-control" }
    .col-md-4
      = f.input :middle_name, input_html: { class: "form-control" }
    .col-md-4
      = f.input :last_name, input_html: { class: "form-control" }
  %hr
  = button_tag type: :submit, class: "btn btn-primary" do
    Save Client Record

  - if client.new_record?
    = link_to clients_path, class: "btn btn-default" do
      Cancel
  - else
    = link_to client_path(client.id), class: "btn btn-default"

app/views/clients/_list.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Client Number
      %th Name
      %th # of Accounts
      %th Actions
  %tbody
    - clients.each do |c|
      %tr
        %td #{c.client_number}
        %td #{c}
        %td #{c.num_accounts}
        %td
          = link_to client_path(c.id), class: "btn btn-primary" do
            Show

app/views/clients/edit.html.haml
%section.content-header
  %h1
    Edit Client #{@client}

%section.content
  .box.box-primary
    .box-body
      = render partial: "form", locals: { client: @client }

app/views/clients/index.html.haml
%section.content-header
  %h1
    Clients Database

%section.content
  .box.box-primary
    .box-body
      = link_to new_client_path, class: "btn btn-primary" do
        New Client

      = render partial: "list", locals: { clients: @clients }

app/views/clients/new.html.haml
%section.content-header
  %h1
    New Client

%section.content
  .box.box-primary
    .box-body
      = render partial: "form", locals: { client: @client }

app/views/clients/show.html.haml
%section.content-header
  %h1
    Client: #{@client}
    %small
      #{@client.client_number}

%section.content
  .box.box-primary
    .box-body
      = link_to edit_client_path(@client), class: "btn btn-info" do
        Edit Client

      = link_to new_client_bank_account_path(@client.id), class: "btn btn-primary" do
        New Bank Account
      = render partial: "bank_accounts", locals: { bank_accounts: @client.bank_accounts }