config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  resources :bank_accounts
  resources :clients do
    resources :bank_accounts, controller: "clients/bank_accounts", except: [:index, :show, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post "bank_accounts/new_transaction", to: "bank_accounts#new_transaction"
    end
  end
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :client

  validates :client, presence: true
  validates :account_number, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: true

  before_validation :load_defaults

  has_many :account_transactions

  def load_defaults
    if new_record?
      self.balance = 0.00
    end
  end

  def to_s
    account_number
  end
  
end

app/controllers/api/v1/bank_accounts_controller.rb
module Api
  module V1
    class BankAccountsController < ApplicationController
      def new_transaction
        amount = params[:amount]
        transaction_type = params[:transaction_type]
        bank_account_id = params[:bank_account_id]

        errors = ::BankAccounts::ValidateNewTransaction.new(
          amount: amount,
          transaction_type: transaction_type,
          bank_account_id: bank_account_id
        ).execute!
        
        if errors.size > 0
          render json: { errors: errors }, status: 402
        else
          bank_account = ::BankAccounts::PerformTransaction.new(
            amount: amount,
            transaction_type: transaction_type,
            bank_account_id: bank_account_id
          ).execute!

          render json: { balance: bank_account.balance }
        end
      end
      
    end
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @bank_accounts = BankAccount.all
  end

  def new
    @bank_account = BankAccount.new
  end

  def create
    @bank_account = BankAccount.new(bank_account_params)

    if @bank_account.save
      redirect_to bank_account_path(@bank_account.id)
    else
      render "new"
    end
  end

  def edit
    @bank_account = BankAccount.find(params[:id])
  end

  def update
    @bank_account = BankAccount.find(params[:id])

    if @bank_account.update(bank_account_params)
      redirect_to bank_account_path(@bank_account.id)
    else
      render "edit"
    end
  end

  def destroy
    bank_account = BankAccount.find(params[:id])
    client       = bank_account.client

    if bank_account.balance > 0
      redirect_to bank_account_path(@bank_account.id)
    else
      @bank_account.destroy!
      redirect_to client_path(client)
    end
  end

  def show
    @bank_account = BankAccount.find(params[:id])
  end

  private
  def bank_account_params
    params.require(:bank_account).permit(:account_number, :client_id)
  end
end

app/controllers/clients/bank_accounts_controller.rb
module Clients
  class BankAccountsController < ApplicationController
    before_action :load_parent_object
    before_action :load_object, only: [:edit, :update]

    def new
      @bank_account = BankAccount.new
    end

    def create
      @bank_account = BankAccount.new(bank_accounts_params)
      @bank_account.client = @client

      if @bank_account.save
        redirect_to bank_account_path(@bank_account.id)
      else
        render "new"
      end
    end

    def edit
    end

    def update
      @bank_account.client = @client
      if @bank_account.update(bank_accounts_params)
        redirect_to bank_account_path(@bank_account.id)
      else
        render "edit"
      end
    end

    private

    def load_parent_object
      @client = Client.find(params[:client_id])
    end

    def load_object
      @bank_account = BankAccount.find(params[:id])
    end

    def bank_accounts_params
      params.require(:bank_account).permit(:account_number )
    end
  end
end

app/views/bank_accounts/_form.html.haml
= simple_form_for bank_account do |f|
  = f.input :account_number, input_html: { class: "form-control" }
  = f.association :client, input_html: { class: "form-control" }

  %hr
  .form-actions
    = button_tag type: :submit, class: "btn btn-primary" do
      Save Bank Account
    = link_to root_path, class: "btn btn-default" do
      Cancel

app/views/bank_accounts/_modal_transaction.html.haml
#modal-transaction.modal.fade.modal-fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type:'button', data:{dismiss:'modal'}}
          %span{aria:{hidden:'true'}}
            %i.fa.fa-close
          %span.sr-only Close
        %h4.modal-title
          New Transaction
      .modal-body
        .row
          .col-md-6
            .notification
        .row
          .col-md-6
            %label
              Amount
            = text_field_tag :amount, 0.00, id: "input-amount", class: "form-control"
          .col-md-6
            %label
              Transaction Type
            = select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: "select-transaction-type", class: "form-control"
      .modal-footer
        %button.btn.btn-default{type:'button', data:{dismiss:'modal'}} Close
        %button#btn-save.btn.btn-primary{type:'button'} Save

app/views/bank_accounts/_transactions.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Date of Transaction
      %th Amount
      %th Transaction
  %tbody
    - bank_account.account_transactions.each do |t|
      %tr
        %td #{t.created_at}
        %td #{t.transaction_type}
        %td #{number_to_currency(t.amount, unit: "N")}
    %tr
      %th
      %th Balance
      %th #{number_to_currency(bank_account.balance, unit: "N")}

app/views/bank_accounts/edit.html.haml
%section.content-header
  %h1
    Edit Bank Account
    %small
      #{@bank_account.account_number}

%section.content
  .box.box-primary
    .box-body
      = render partial: "form", locals: {bank_account: @bank_account}

app/views/bank_accounts/index.html.haml
%section.content-header
  %h1
    Bank Accounts

%section.content
  .box.box-primary
    .box-body
      = link_to new_bank_account_path, class: "btn btn-primary" do
        New Bank Account

      %table.table.table-bordered
        %thead
          %tr
            %th Account Number
            %th Client
            %th Balance
            %th Actions
        %tbody
          - @bank_accounts.each do |bank_account|
            %tr
            %td #{bank_account.account_number}
            %td 
              = link_to client_path(bank_account.client.id) do
                #{bank_account.client}
            %td #{number_to_currency(bank_account.balance, unit: "N")}
            %td
              = link_to bank_account_path(bank_account.id), class: "btn btn-primary" do
                Show

app/views/bank_accounts/new.html.haml
%section.content-header
  %h1
    New Bank Account

%section.content
  .box.box-primary
    .box-body
= render partial: "form", locals: {bank_account: @bank_account}

app/views/bank_accounts/show.html.haml
%section.content-header
  %h1
    Account Number: #{@bank_account.account_number}
    %small
      #{@bank_account.client}

%section.content
  .box.box-primary
    .box-body
      = button_tag :new_transaction, id: "btn-new-transaction", class: "btn btn-primary" do
        New Transaction

      = link_to client_path(@bank_account.client.id), class: "btn btn-default" do
        Back to #{@bank_account.client}

      = link_to bank_accounts_path, class: "btn btn-default" do
        Back to Bank Accounts

      = render partial: "transactions", locals: {bank_account: @bank_account}
      = link_to edit_bank_account_path(@bank_account.id), class: "btn btn-info" do
        Edit Bank Account

      = link_to bank_account_path(@bank_account.id), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} do
        Delete

= render partial: "modal_transaction"
#parameters{ data: { bank_account_id: @bank_account.id } }

= javascript_include_tag "bootstrap.js"
= javascript_include_tag "bank_accounts/Show"
:javascript
  $(document).ready(function() {
    Show.init();
  });